# Specify tool names or modules to allow (specifying module allow all tools within)
ALLOW_LIST:
  - ExactMolWt
  - rdkit_mcp.Chem.Descriptors

# Specify tool names or modules to block (specifying module block all tools within)
BLOCK_LIST:
  - ExactMolWt
  - rdkit_mcp.Chem.Descriptors

# Directory where tools can write output files
FILE_DIR: /home/user/workspace/rdkit-mcp-server/outputs/
